apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd:frontend
spec:
  template:
    metadata:
      name: httpd:frontend
    spec:
      # for images below: has to be exact as dockerhub
      # if using another repo for images specify full path
      containers:
      - name: httpd:frontendsvc
        image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      name: httpd:frontend