# My First Pod !
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
  # can be anything relevant here
    app: nginx
    tier: frontend
spec:
# for images below: has to be exact as dockerhub
# if using another repo for images specify full path
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: busybox

# use kubectl apply to create new object
# kubectl apply -f pod.yaml
# use kubectl get pods to check if created
# use kubectl describe pod nginx / busybox to see more details about pod
